### ISSUE TITLE
Publish latest version on npm

### ISSUE THREAD

**Issue by dpaez** [hypermodules/level-hookdown#32]
Hi @bcomnes 👋 Hope you are having a good day!

It seems like the npm published version (3.1.1) is one patch behind `master` (3.1.2) repo version. I noticed when I try to update the level-auto-index version from GEUT's fork to the latest npm version. (related to https://github.com/p2pcommons/sdk-js/issues/33)

**Comment by bcomnes** [comment]
Fixed! Sorry about that
